
volumes:
  postgres_data: 
  
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14.13  

    volumes:  # Volumes specific to the db service
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: book_store_user
      POSTGRES_PASSWORD: book_store
      POSTGRES_DB: book_store
    ports:
      - "5432:5432"
